name = "EvalCurves"
uuid = "f38dcc0d-dce9-59d8-8cbc-ed225c093724"
authors = ["Vít Škvára <vit.skvara@gmail.com>"]
repository = "https://github.com/vitskvara/EvalCurves.jl.git"
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
