name = "EvalCurves"
uuid = "f38dcc0d-dce9-59d8-8cbc-ed225c093724"
authors = ["Vít Škvára <vit.skvara@gmail.com>"]
repository = "https://github.com/vitskvara/EvalCurves.jl.git"
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
